In [1]:
import os
import json
import pandas as pd


data_folder = "."  # aynı klasör
file_list = [f for f in os.listdir(data_folder) if f.endswith(".txt")]


all_records = []

# Dosyaları sırayla işle
for filename in sorted(file_list):
    file_path = os.path.join(data_folder, filename)
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    for day in data.get("days", []):
        for hour in day.get("hours", []):
            hour_record = hour.copy()
            hour_record["date"] = day["datetime"]
            all_records.append(hour_record)


weather_df = pd.DataFrame(all_records)

# Tarih + saat birleştir
weather_df["datetime"] = pd.to_datetime(weather_df["date"] + " " + weather_df["datetime"])
weather_df.drop(columns=["date"], inplace=True)

# Gereksiz sütunları çıkar
weather_df.drop(columns=['datetimeEpoch', 'stations', 'source','preciptype'], errors='ignore', inplace=True)


weather_df.sort_values("datetime", inplace=True)
weather_df.reset_index(drop=True, inplace=True)


print(weather_df.head())
print(weather_df["datetime"].min(), "→", weather_df["datetime"].max())

             datetime  temp  feelslike  humidity  dew  precip  precipprob  \
0 2022-01-02 00:00:00  10.0       10.0     87.38  8.0     0.0         0.0
1 2022-01-02 01:00:00  10.0       10.0     87.38  8.0     0.0         0.0
2 2022-01-02 02:00:00  10.0       10.0     87.38  8.0     0.0         0.0
3 2022-01-02 03:00:00  10.0       10.0     87.38  8.0     0.0         0.0
4 2022-01-02 04:00:00   9.0        9.0     93.45  8.0     0.0         0.0

   snow  snowdepth  windgust  windspeed  winddir  pressure  visibility  \
0   0.0        0.0      16.6        9.4    250.0    1020.0         9.0
1   0.0        0.0      15.5       13.0    260.0    1021.0        10.0
2   0.0        0.0      15.8       13.0    260.0    1021.0        10.0
3   0.0        0.0      15.5        5.4    250.0    1021.0        10.0
4   0.0        0.0      14.4        0.0      0.0    1021.0        10.0

   cloudcover  solarradiation  solarenergy  uvindex        conditions  \
0        50.0             0.0          0.0      0.0  Partially cloudy
1        50.0             0.0          0.0      0.0  Partially cloudy
2        50.0             0.0          0.0      0.0  Partially cloudy
3        50.0             0.0          0.0      0.0  Partially cloudy
4        50.0             0.0          0.0      0.0  Partially cloudy

                  icon
0  partly-cloudy-night
1  partly-cloudy-night
2  partly-cloudy-night
3  partly-cloudy-night
4  partly-cloudy-night
2022-01-02 00:00:00 → 2025-05-01 23:00:00

In [2]:
display(weather_df.tail(395))

,datetime,temp,feelslike,humidity,dew,precip,precipprob,snow,snowdepth,windgust,windspeed,winddir,pressure,visibility,cloudcover,solarradiation,solarenergy,uvindex,conditions,icon
28789,2025-04-15 13:00:00,15.8,15.8,50.28,5.5,0.0,0.0,0.0,0.0,22.7,13.0,184.0,1024.0,10.0,0.0,870.1,3.1,9.0,Clear,clear-day
28790,2025-04-15 14:00:00,16.0,16.0,55.15,7.0,0.0,0.0,0.0,0.0,22.0,9.8,230.0,1024.0,10.0,0.0,874.6,3.1,9.0,Clear,clear-day
28791,2025-04-15 15:00:00,15.4,15.4,54.38,6.2,0.0,0.0,0.0,0.0,22.0,14.1,236.0,1023.0,10.0,0.0,816.9,2.9,8.0,Clear,clear-day
28792,2025-04-15 16:00:00,17.0,17.0,50.39,6.6,0.0,0.0,0.0,0.0,21.2,11.2,246.0,1023.0,10.0,4.7,703.0,2.5,7.0,Clear,clear-day
28793,2025-04-15 17:00:00,19.0,19.0,39.13,4.8,0.0,0.0,0.0,0.0,24.5,12.6,40.0,1023.0,10.0,23.9,544.9,2.0,5.0,Partially cloudy,partly-cloudy-day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29179,2025-05-01 19:00:00,12.0,12.0,76.51,8.0,0.0,0.0,0.0,0.0,33.5,20.5,40.0,1013.0,10.0,88.0,NaN,NaN,NaN,Partially cloudy,partly-cloudy-day
29180,2025-05-01 20:00:00,11.0,11.0,81.74,8.0,0.0,0.0,0.0,0.0,32.0,20.5,20.0,1014.0,10.0,88.0,NaN,NaN,NaN,Partially cloudy,partly-cloudy-day
29181,2025-05-01 21:00:00,11.0,11.0,81.74,8.0,0.0,0.0,0.0,0.0,23.8,20.5,20.0,1014.0,10.0,88.0,NaN,NaN,NaN,Partially cloudy,partly-cloudy-night
29182,2025-05-01 22:00:00,11.0,11.0,81.74,8.0,0.0,0.0,0.0,0.0,24.8,18.4,30.0,1015.0,10.0,88.0,NaN,NaN,NaN,Partially cloudy,partly-cloudy-night
29183,2025-05-01 23:00:00,11.0,11.0,81.74,8.0,0.2,100.0,0.0,0.0,22.7,18.4,20.0,1015.0,10.0,88.0,NaN,NaN,NaN,"Rain, Partially cloudy",rain

In [3]:
weather_df.to_csv("visualcrossing_weather_2022_2025.csv", index=False)

In [4]:
import pandas as pd
import os


files = {
    "Yenibosna": "Yenibosna_istasyon.xlsx",
    "Şirinevler": "Şirinevler_istasyon.xlsx",
    "Bağcılar": "Bağcılar_istasyon.xlsx",
    "Sultangazi": "Sultangazi_istasyon.xlsx",
    "Esenyurt": "Esenyurt_istasyon.xlsx"
}

# Hedef kolon adları 
target_cols = ['datetime', 'PM10', 'SO2', 'CO', 'NO2', 'NOX', 'NO', 'O3']

all_dfs = []

for istasyon_adi, file in files.items():
    df = pd.read_excel(file)
    
    # İlk satırıu sil
    df = df.iloc[1:].reset_index(drop=True)
    df.columns = target_cols[:len(df.columns)]
    
    
    df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')
    df['datetime'] = df['datetime'].dt.floor('H')  # Saatlik yuvarla

    
    for col in df.columns:
        if col != "datetime":
            df[col] = df[col].astype(str).str.replace('.', '', regex=False)
            df[col] = df[col].str.replace(',', '.', regex=False)
            df[col] = pd.to_numeric(df[col], errors='coerce')
    
    df['istasyon'] = istasyon_adi
    all_dfs.append(df)

# Tüm istasyonları birleştir
df_all = pd.concat(all_dfs, ignore_index=True)

print(df_all.head())

e:\Anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\emin8\AppData\Local\Temp\ipykernel_13968\1410685725.py:27: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df['datetime'] = df['datetime'].dt.floor('H')  # Saatlik yuvarla
e:\Anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\emin8\AppData\Local\Temp\ipykernel_13968\1410685725.py:27: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df['datetime'] = df['datetime'].dt.floor('H')  # Saatlik yuvarla
e:\Anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\emin8\AppData\Local\Temp\ipykernel_13968\1410685725.py:27: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df['datetime'] = df['datetime'].dt.floor('H')  # Saatlik yuvarla
e:\Anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\emin8\AppData\Local\Temp\ipykernel_13968\1410685725.py:27: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df['datetime'] = df['datetime'].dt.floor('H')  # Saatlik yuvarla
e:\Anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

             datetime  PM10  SO2     CO   NO2    NOX    NO  O3   istasyon
0 2022-01-01 12:00:00   4.1  1.0  692.8  41.4  133.3  59.9 NaN  Yenibosna
1 2022-01-01 13:00:00   3.2  1.3  555.8  42.9  141.2  66.7 NaN  Yenibosna
2 2022-01-01 14:00:00   3.4  1.2  642.1  40.8  123.6  54.0 NaN  Yenibosna
3 2022-01-01 15:00:00   3.3  1.2  770.3  42.6  127.7  55.4 NaN  Yenibosna
4 2022-01-01 16:00:00   3.1  1.4  854.1  51.4  160.0  71.0 NaN  Yenibosna

C:\Users\emin8\AppData\Local\Temp\ipykernel_13968\1410685725.py:27: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df['datetime'] = df['datetime'].dt.floor('H')  # Saatlik yuvarla

In [5]:
display(df_all.head())
df_all.shape

             datetime  PM10  SO2     CO   NO2    NOX    NO  O3   istasyon
0 2022-01-01 12:00:00   4.1  1.0  692.8  41.4  133.3  59.9 NaN  Yenibosna
1 2022-01-01 13:00:00   3.2  1.3  555.8  42.9  141.2  66.7 NaN  Yenibosna
2 2022-01-01 14:00:00   3.4  1.2  642.1  40.8  123.6  54.0 NaN  Yenibosna
3 2022-01-01 15:00:00   3.3  1.2  770.3  42.6  127.7  55.4 NaN  Yenibosna
4 2022-01-01 16:00:00   3.1  1.4  854.1  51.4  160.0  71.0 NaN  Yenibosna

(146045, 9)

In [6]:
kirleticiler = ['PM10', 'SO2', 'CO', 'NO2', 'NOX', 'NO', 'O3']

# Saatlik ortalama: tüm istasyonlardan gelen değerlerin ortalaması
df_avg = df_all.groupby("datetime")[kirleticiler].mean().reset_index()

print(df_avg.head())
print(df_avg.shape)

             datetime    PM10    SO2       CO      NO2     NOX      NO    O3
0 2022-01-01 12:00:00  30.460  3.350  496.546  33.2775  66.328  39.898  28.0
1 2022-01-01 13:00:00  32.770  3.272  497.982  34.7575  62.454  37.670  30.1
2 2022-01-01 14:00:00  32.554  3.394  506.738  41.7150  63.026  33.364  27.2
3 2022-01-01 15:00:00  31.760  3.972  578.760  43.7350  75.722  40.112  23.9
4 2022-01-01 16:00:00  31.116  3.988  576.256  45.3875  82.098  43.130  21.3
(29209, 8)

In [7]:
display(df_avg.tail())

,datetime,PM10,SO2,CO,NO2,NOX,NO,O3
29204,2025-05-02 08:00:00,47.548,3.9200,848.144,128.6025,78.190,22.318,24.2
29205,2025-05-02 09:00:00,49.012,4.0625,919.320,121.0650,77.924,28.106,42.4
29206,2025-05-02 10:00:00,48.282,3.8975,836.586,90.0175,58.220,31.246,53.6
29207,2025-05-02 11:00:00,43.014,4.3350,800.614,85.5225,54.348,32.880,55.4
29208,2025-05-02 12:00:00,42.014,4.4600,890.598,80.0750,49.988,34.930,71.2

In [8]:
df_avg.dtypes

datetime    datetime64[ns]
PM10               float64
SO2                float64
CO                 float64
NO2                float64
NOX                float64
NO                 float64
O3                 float64
dtype: object

In [9]:
weather_df.dtypes

datetime          datetime64[ns]
temp                     float64
feelslike                float64
humidity                 float64
dew                      float64
precip                   float64
precipprob               float64
snow                     float64
snowdepth                float64
windgust                 float64
windspeed                float64
winddir                  float64
pressure                 float64
visibility               float64
cloudcover               float64
solarradiation           float64
solarenergy              float64
uvindex                  float64
conditions                object
icon                      object
dtype: object

In [10]:
# Merge işlemi saate göre
df_model = pd.merge(df_avg, weather_df, on="datetime", how="inner")

df_model = df_model.sort_values("datetime").reset_index(drop=True)

print(df_model.head())
print(df_model.shape)

             datetime    PM10    SO2       CO       NO2      NOX      NO   O3  \
0 2022-01-02 00:00:00  47.976  2.622  633.510   91.5125  123.564  44.600  4.0
1 2022-01-02 01:00:00  50.498  2.786  537.026   90.1475  121.566  43.642  3.6
2 2022-01-02 02:00:00  47.264  3.456  615.502  102.6875  119.832  39.820  3.4
3 2022-01-02 03:00:00  46.026  3.260  693.612   82.3575  120.728  46.062  3.7
4 2022-01-02 04:00:00  47.514  3.252  626.874   54.8325   97.116  41.600  4.0

   temp  feelslike  ...  windspeed  winddir  pressure  visibility  cloudcover  \
0  10.0       10.0  ...        9.4    250.0    1020.0         9.0        50.0
1  10.0       10.0  ...       13.0    260.0    1021.0        10.0        50.0
2  10.0       10.0  ...       13.0    260.0    1021.0        10.0        50.0
3  10.0       10.0  ...        5.4    250.0    1021.0        10.0        50.0
4   9.0        9.0  ...        0.0      0.0    1021.0        10.0        50.0

   solarradiation  solarenergy  uvindex        conditions                 icon
0             0.0          0.0      0.0  Partially cloudy  partly-cloudy-night
1             0.0          0.0      0.0  Partially cloudy  partly-cloudy-night
2             0.0          0.0      0.0  Partially cloudy  partly-cloudy-night
3             0.0          0.0      0.0  Partially cloudy  partly-cloudy-night
4             0.0          0.0      0.0  Partially cloudy  partly-cloudy-night

[5 rows x 27 columns]
(29184, 27)

In [11]:
display(df_model.head())

,datetime,PM10,SO2,CO,NO2,NOX,NO,O3,temp,feelslike,...,windspeed,winddir,pressure,visibility,cloudcover,solarradiation,solarenergy,uvindex,conditions,icon
0,2022-01-02 00:00:00,47.976,2.622,633.510,91.5125,123.564,44.600,4.0,10.0,10.0,...,9.4,250.0,1020.0,9.0,50.0,0.0,0.0,0.0,Partially cloudy,partly-cloudy-night
1,2022-01-02 01:00:00,50.498,2.786,537.026,90.1475,121.566,43.642,3.6,10.0,10.0,...,13.0,260.0,1021.0,10.0,50.0,0.0,0.0,0.0,Partially cloudy,partly-cloudy-night
2,2022-01-02 02:00:00,47.264,3.456,615.502,102.6875,119.832,39.820,3.4,10.0,10.0,...,13.0,260.0,1021.0,10.0,50.0,0.0,0.0,0.0,Partially cloudy,partly-cloudy-night
3,2022-01-02 03:00:00,46.026,3.260,693.612,82.3575,120.728,46.062,3.7,10.0,10.0,...,5.4,250.0,1021.0,10.0,50.0,0.0,0.0,0.0,Partially cloudy,partly-cloudy-night
4,2022-01-02 04:00:00,47.514,3.252,626.874,54.8325,97.116,41.600,4.0,9.0,9.0,...,0.0,0.0,1021.0,10.0,50.0,0.0,0.0,0.0,Partially cloudy,partly-cloudy-night

In [12]:
df_model.to_csv("merged.csv", index=False)